main-6502-vasm_std:
	vasm6502_std -Fbin hello-vasm_std.asm -o hello-vasm_std.bin
main-6502-vasm_oldstyle:
	vasm6502_oldstyle -Fbin hello-vasm_oldstyle.asm -o hello-vasm_oldstyle.bin
main-6502-asm6:
	asm6 hello-asm6.asm hello-asm6.bin
main-6502-run:
	java -jar ~/symon-1.5.0.jar -machine symon
