#!/bin/bash

if [ $# -eq 0 ]
then
 echo "Enter the name of a RISC-V assembly source file to run it."
fi 

if [ $# -ne 0 ] # if the number of arguments is not equal to zero
then
 java -jar ~/rars.jar $1
fi

