main-6502-vasm_oldstyle:
	vasm6502_oldstyle  C64_HelloWorld.asm -cbm-prg -Fbin -o C64_HelloWorld.prg
extra:
	vasm6502_oldstyle  C64_HelloWorld.asm -cbm-prg -Fbin -o C64_HelloWorld.prg -L Listing.txt -chklabels
